/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author User
 */
public class latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form latihan3
     */
    public latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JK = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Idnama = new javax.swing.JTextField();
        Idbb = new javax.swing.JTextField();
        Idtb = new javax.swing.JTextField();
        LL = new javax.swing.JRadioButton();
        P = new javax.swing.JRadioButton();
        ulangi = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idha = new javax.swing.JTextField();
        idsaran = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CEK KESEHATAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 20, 160, 22);

        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 60, 34, 16);

        jLabel3.setText("BERAT BADAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 100, 90, 16);

        jLabel4.setText("TINGGI BADAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 140, 83, 16);

        jLabel5.setText("JENIS KELAMIN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 170, 100, 30);

        Idnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdnamaActionPerformed(evt);
            }
        });
        getContentPane().add(Idnama);
        Idnama.setBounds(310, 60, 280, 22);

        Idbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdbbActionPerformed(evt);
            }
        });
        getContentPane().add(Idbb);
        Idbb.setBounds(310, 100, 280, 22);
        getContentPane().add(Idtb);
        Idtb.setBounds(310, 140, 280, 22);

        JK.add(LL);
        LL.setText("Laki-Laki");
        LL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLActionPerformed(evt);
            }
        });
        getContentPane().add(LL);
        LL.setBounds(310, 180, 77, 25);

        JK.add(P);
        P.setText("Perempuan");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        getContentPane().add(P);
        P.setBounds(480, 180, 93, 25);

        ulangi.setText("ULANGI");
        ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangiActionPerformed(evt);
            }
        });
        getContentPane().add(ulangi);
        ulangi.setBounds(400, 220, 75, 25);

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(510, 220, 77, 25);

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(290, 220, 77, 25);

        jLabel6.setText("Berat badan ideal adalah :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 270, 160, 16);

        idd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddActionPerformed(evt);
            }
        });
        getContentPane().add(idd);
        idd.setBounds(360, 270, 70, 22);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 270, 41, 20);

        jLabel8.setText("kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(600, 100, 13, 16);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 140, 41, 16);

        jLabel10.setText("Hasil Analisa Kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 310, 140, 16);

        idha.setText("?");
        getContentPane().add(idha);
        idha.setBounds(190, 340, 500, 22);

        idsaran.setText("Saran ?");
        getContentPane().add(idsaran);
        idsaran.setBounds(190, 370, 500, 22);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 50, 470, 160);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(290, 220, 300, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/kesehatan.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 960, 460);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(160, 260, 550, 150);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/riaugreen_Buruknya-Pelayanan-Kesehatan-Terhadap-Masyarakat-Miskin.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 90, 870, 380);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/sehat.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 570, 230);

        setBounds(0, 0, 974, 511);
    }// </editor-fold>//GEN-END:initComponents

    private void IdbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdbbActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
      double t, b, h = 0;
      t = Double.valueOf(Idtb.getText());
      b = Double.valueOf(Idbb.getText());
      String nm = Idnama.getText();
      //pilihan jenis kelamin
      if(LL.isSelected()){
          h = (t-100);
      }else if(P.isSelected()){
          h = (t-104);
      }
      String temp = Double.toString(h);
      //logika untuk analisa hasil kesehatan
      if(h<b){
          idd.setText(temp);
          idha.setText("maaf "+nm+" anda kelebihan berat badan");
          idsaran.setText("olahraga teratur dan jaga pola makan");
      }else if(h>b){
          idd.setText(temp);
          idha.setText("maaf "+nm+" anda kekurangan berat badan");
          idsaran.setText("makan yang banyak dan makanlah makanan bergizi");
      }else{
          idd.setText(temp);
          idha.setText("Berat badan anda sudah ideal");
          idsaran.setText("Pertahankan");
      }
    }//GEN-LAST:event_hitungActionPerformed

    private void LLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LLActionPerformed

    private void iddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddActionPerformed

    private void IdnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdnamaActionPerformed
        // TODO add your handling code here:
        Idnama.getText();
        Idbb.getText();
        Idtb.getText();
    }//GEN-LAST:event_IdnamaActionPerformed

    private void ulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangiActionPerformed
        // TODO add your handling code here:
        Idnama.setText("");
        Idbb.setText("");
        Idtb.setText("");
        idd.setText("");
        idha.setText("");
        idsaran.setText("");
        
        JK.clearSelection();
    }//GEN-LAST:event_ulangiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Idbb;
    private javax.swing.JTextField Idnama;
    private javax.swing.JTextField Idtb;
    private javax.swing.ButtonGroup JK;
    private javax.swing.JRadioButton LL;
    private javax.swing.JRadioButton P;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField idd;
    private javax.swing.JTextField idha;
    private javax.swing.JTextField idsaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton keluar;
    private javax.swing.JButton ulangi;
    // End of variables declaration//GEN-END:variables
}
