/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author User
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihanjurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        varnama = new javax.swing.JTextField();
        absen = new javax.swing.JLabel();
        varabsen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdbrpl = new javax.swing.JRadioButton();
        rdbtkj = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbprogramming = new javax.swing.JCheckBox();
        cbanimator = new javax.swing.JCheckBox();
        cbdesaigner = new javax.swing.JCheckBox();
        cbvideoediting = new javax.swing.JCheckBox();
        btnsubmit = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        hasil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 33, 84, 22);

        nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama.setText("NAMA");
        getContentPane().add(nama);
        nama.setBounds(246, 80, 43, 17);

        varnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varnamaActionPerformed(evt);
            }
        });
        getContentPane().add(varnama);
        varnama.setBounds(356, 73, 210, 32);

        absen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        absen.setText("ABSEN");
        getContentPane().add(absen);
        absen.setBounds(246, 130, 49, 17);
        getContentPane().add(varabsen);
        varabsen.setBounds(356, 123, 210, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("JURUSAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(246, 176, 67, 17);

        pilihanjurusan.add(rdbrpl);
        rdbrpl.setText("RPL");
        getContentPane().add(rdbrpl);
        rdbrpl.setBounds(356, 173, 49, 25);

        pilihanjurusan.add(rdbtkj);
        rdbtkj.setText("TKJ");
        getContentPane().add(rdbtkj);
        rdbtkj.setBounds(466, 173, 49, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("HOBI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(246, 219, 39, 17);

        cbprogramming.setText("Programming");
        getContentPane().add(cbprogramming);
        cbprogramming.setBounds(356, 216, 105, 25);

        cbanimator.setText("Animator");
        getContentPane().add(cbanimator);
        cbanimator.setBounds(479, 216, 81, 25);

        cbdesaigner.setText("Desaigner");
        getContentPane().add(cbdesaigner);
        cbdesaigner.setBounds(356, 246, 85, 25);

        cbvideoediting.setText("Video Editing");
        getContentPane().add(cbvideoediting);
        cbvideoediting.setBounds(479, 246, 103, 25);

        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit);
        btnsubmit.setBounds(314, 289, 77, 25);

        btnremove.setText("REMOVE");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnremove);
        btnremove.setBounds(409, 289, 81, 25);

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit);
        btnexit.setBounds(508, 289, 59, 25);

        hasil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hasil.setText("HASIL");
        getContentPane().add(hasil);
        hasil.setBounds(293, 321, 45, 17);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane1.setViewportView(TAHasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(293, 345, 289, 116);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 70, 41, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varnamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_varnamaActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String nama = varnama.getText();
        String absen = varabsen.getText();
        String jurusan;
        String hobi ="";
        
        // untuk pilihan jurusan 
        if (rdbrpl.isSelected())
            jurusan= "RPL";
        else if (rdbtkj.isSelected())
            jurusan= "TKJ";
        else
            jurusan= " ";
        
        //untuk pilihan checkbox
        if (cbprogramming.isSelected())
            hobi+=cbprogramming.getText()+",    ";
        if (cbanimator.isSelected())
            hobi+=cbanimator.getText()+",    ";
        if (cbdesaigner.isSelected())
            hobi+=cbdesaigner.getText()+",    ";
        if (cbvideoediting.isSelected())
            hobi+=cbvideoediting.getText()+",    ";
        //untuk hasil
        TAHasil.setText("nama anda : "+nama+ "\n Absen anda : " +absen+ "\n Jurusan anda: " +jurusan+ "\n hobi anda: " +hobi);
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        varnama.setText("");
        varabsen.setText("");
        pilihanjurusan.clearSelection();
        hasil.setText("");
        cbprogramming.setSelected(false);
        cbanimator.setSelected(false);
        cbdesaigner.setSelected(false);
        cbvideoediting.setSelected(false);
        
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JLabel absen;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JCheckBox cbanimator;
    private javax.swing.JCheckBox cbdesaigner;
    private javax.swing.JCheckBox cbprogramming;
    private javax.swing.JCheckBox cbvideoediting;
    private javax.swing.JLabel hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.ButtonGroup pilihanjurusan;
    private javax.swing.JRadioButton rdbrpl;
    private javax.swing.JRadioButton rdbtkj;
    private javax.swing.JTextField varabsen;
    private javax.swing.JTextField varnama;
    // End of variables declaration//GEN-END:variables
}
