/*  
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author User
 */
public class Latihan4 extends javax.swing.JFrame {
String bil="";
double jumlah,bilangan1,bilangan2;
int pilih;
    /**
     * Creates new form Latihan4
     */
    public Latihan4() {
        initComponents();
             
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tampilan = new javax.swing.JTextField();
        bil0 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        hapus2 = new javax.swing.JButton();
        hapus3 = new javax.swing.JButton();
        plusmin = new javax.swing.JButton();
        bil8 = new javax.swing.JButton();
        bil7 = new javax.swing.JButton();
        bil4 = new javax.swing.JButton();
        bil1 = new javax.swing.JButton();
        bil9 = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        bil5 = new javax.swing.JButton();
        bil6 = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        satuperx = new javax.swing.JButton();
        bil2 = new javax.swing.JButton();
        bil3 = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        hasil = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        getContentPane().setLayout(null);

        tampilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilanActionPerformed(evt);
            }
        });
        getContentPane().add(tampilan);
        tampilan.setBounds(31, 13, 640, 80);

        bil0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil0.setText("0");
        bil0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil0ActionPerformed(evt);
            }
        });
        getContentPane().add(bil0);
        bil0.setBounds(30, 390, 250, 60);

        hapus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hapus.setText("←");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(30, 110, 120, 60);

        hapus2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hapus2.setText("%");
        hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus2ActionPerformed(evt);
            }
        });
        getContentPane().add(hapus2);
        hapus2.setBounds(160, 110, 120, 60);

        hapus3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hapus3.setText("C");
        hapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus3ActionPerformed(evt);
            }
        });
        getContentPane().add(hapus3);
        hapus3.setBounds(290, 110, 120, 60);

        plusmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusmin.setText("±");
        plusmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminActionPerformed(evt);
            }
        });
        getContentPane().add(plusmin);
        plusmin.setBounds(420, 110, 120, 60);

        bil8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil8.setText("8");
        bil8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil8ActionPerformed(evt);
            }
        });
        getContentPane().add(bil8);
        bil8.setBounds(160, 180, 120, 60);

        bil7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil7.setText("7");
        bil7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil7ActionPerformed(evt);
            }
        });
        getContentPane().add(bil7);
        bil7.setBounds(30, 180, 120, 60);

        bil4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil4.setText("4");
        bil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil4ActionPerformed(evt);
            }
        });
        getContentPane().add(bil4);
        bil4.setBounds(30, 250, 120, 60);

        bil1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil1.setText("1");
        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        getContentPane().add(bil1);
        bil1.setBounds(30, 320, 120, 60);

        bil9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil9.setText("9");
        bil9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil9ActionPerformed(evt);
            }
        });
        getContentPane().add(bil9);
        bil9.setBounds(290, 180, 120, 60);

        bagi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi);
        bagi.setBounds(420, 180, 120, 60);

        pangkat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pangkat.setText("√");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        getContentPane().add(pangkat);
        pangkat.setBounds(550, 110, 120, 60);

        persen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        persen.setText("MOD");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        getContentPane().add(persen);
        persen.setBounds(550, 180, 120, 60);

        bil5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil5.setText("5");
        bil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil5ActionPerformed(evt);
            }
        });
        getContentPane().add(bil5);
        bil5.setBounds(160, 250, 120, 60);

        bil6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil6.setText("6");
        bil6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil6ActionPerformed(evt);
            }
        });
        getContentPane().add(bil6);
        bil6.setBounds(290, 250, 120, 60);

        kali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(420, 250, 120, 60);

        satuperx.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        satuperx.setText("^");
        satuperx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuperxActionPerformed(evt);
            }
        });
        getContentPane().add(satuperx);
        satuperx.setBounds(550, 250, 120, 60);

        bil2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil2.setText("2");
        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });
        getContentPane().add(bil2);
        bil2.setBounds(160, 320, 120, 60);

        bil3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bil3.setText("3");
        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });
        getContentPane().add(bil3);
        bil3.setBounds(290, 320, 120, 60);

        kurang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang);
        kurang.setBounds(420, 320, 120, 60);

        hasil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hasil.setText("=");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(550, 320, 120, 130);

        tambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(420, 390, 120, 60);

        titik.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        getContentPane().add(titik);
        titik.setBounds(290, 390, 120, 60);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/kalku.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(51, 40, 650, 480);

        setSize(new java.awt.Dimension(722, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 + bilangan2;
            bil = Double.toString(jumlah);
            tampilan.setText(bil);
            break;
        case 2:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 - bilangan2;
            bil = Double.toString(jumlah);
            tampilan.setText(bil);
            break;
        case 3:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 * bilangan2;
            bil = Double.toString(jumlah);
            tampilan.setText(bil);
            break;
        case 4:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 / bilangan2;
            bil = Double.toString(jumlah);
            tampilan.setText(bil);
            break;
        case 5:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 % bilangan2;
            bil = Double.toString(jumlah);
            tampilan.setText(bil);
            break;
        case 6:
            bilangan2 = Double.parseDouble(bil);
            jumlah = Math.pow(bilangan1,bilangan2);
            bil = Double.toString(jumlah);
            tampilan.setText(bil);
            break;
    
            
        default:
            break;
} 
    }//GEN-LAST:event_hasilActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
       bilangan1 = Double.parseDouble(bil);
tampilan.setText("+");
bil="";
pilih=1;
    }//GEN-LAST:event_tambahActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titikActionPerformed

    private void tampilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tampilanActionPerformed

    private void bil0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil0ActionPerformed
        // TODO add your handling code here:
        
        bil +="0";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil0ActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
        bil +="1";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil1ActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
        // TODO add your handling code here:
        bil +="2";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil2ActionPerformed

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
        // TODO add your handling code here:
        bil +="3";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil3ActionPerformed

    private void bil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil4ActionPerformed
        // TODO add your handling code here:
        bil +="4";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil4ActionPerformed

    private void bil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil5ActionPerformed
        // TODO add your handling code here:
        bil +="5";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil5ActionPerformed

    private void bil6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil6ActionPerformed
        // TODO add your handling code here:
        bil +="6";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil6ActionPerformed

    private void bil7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil7ActionPerformed
        // TODO add your handling code here:
        bil +="7";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil7ActionPerformed

    private void bil8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil8ActionPerformed
        // TODO add your handling code here:
        bil +="8";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil8ActionPerformed

    private void bil9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil9ActionPerformed
        // TODO add your handling code here:
        bil +="9";
        tampilan.setText(bil);
    }//GEN-LAST:event_bil9ActionPerformed

    private void hapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus3ActionPerformed
        // TODO add your handling code here:
        
bilangan1=0.0;
bilangan2=0.0;
jumlah=0.0;
bil="";
tampilan.setText("");
    }//GEN-LAST:event_hapus3ActionPerformed

    private void hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus2ActionPerformed
        // TODO add your handling code here:
  bilangan1=Double.parseDouble(bil);
jumlah = bilangan1 *1/100;
 bil = Double.toString(jumlah);           
 tampilan.setText(bil);
            
    }//GEN-LAST:event_hapus2ActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bil);
tampilan.setText("-");
bil="";
pilih=2;
    }//GEN-LAST:event_kurangActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bil);
tampilan.setText("*");
bil="";
pilih=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bil);
tampilan.setText("/");
bil="";
pilih=4;
    }//GEN-LAST:event_bagiActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
                bilangan1=Double.parseDouble(bil);
tampilan.setText("%");
bil="";
pilih=5;
    }//GEN-LAST:event_persenActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        // TODO add your handling code here:
      bilangan1=Double.parseDouble(bil);
        bilangan2 = 2.0;
            jumlah = Math.sqrt(bilangan1);
            bil = Double.toString(jumlah);
            tampilan.setText(bil);
    }//GEN-LAST:event_pangkatActionPerformed

    private void satuperxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuperxActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bil);
        tampilan.setText("^");
        bil ="";
        pilih=6;
    }//GEN-LAST:event_satuperxActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
     tampilan.getText().length();
StringBuilder all = new StringBuilder (tampilan.getText());
char end = all.charAt(all.length()-1);
all.deleteCharAt(all.length()-1);
tampilan.setText(all.toString());
bil = tampilan.getText();
if (tampilan.getText().length() == 0){
    hapus.setEnabled(false);
    titik.setEnabled(true);
    bagi.setEnabled(false);
    kali.setEnabled(false);
    tambah.setEnabled(false);
}
    }//GEN-LAST:event_hapusActionPerformed

    private void plusminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bil);
        tampilan.setText("-"+bilangan1);
        bil ="";
        pilih=8;
    }//GEN-LAST:event_plusminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.JButton bil0;
    private javax.swing.JButton bil1;
    private javax.swing.JButton bil2;
    private javax.swing.JButton bil3;
    private javax.swing.JButton bil4;
    private javax.swing.JButton bil5;
    private javax.swing.JButton bil6;
    private javax.swing.JButton bil7;
    private javax.swing.JButton bil8;
    private javax.swing.JButton bil9;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus2;
    private javax.swing.JButton hapus3;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton persen;
    private javax.swing.JButton plusmin;
    private javax.swing.JButton satuperx;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tampilan;
    private javax.swing.JButton titik;
    // End of variables declaration//GEN-END:variables
}
